/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ScanType = IDL.Variant({ 'dns' : IDL.Null, 'url' : IDL.Null });
export const ResultSummary = IDL.Record({
  'threatsFound' : IDL.Vec(IDL.Text),
  'recordType' : IDL.Text,
  'verdict' : IDL.Text,
  'resolverName' : IDL.Text,
  'recordValue' : IDL.Text,
  'riskScore' : IDL.Nat,
});
export const Time = IDL.Int;
export const ScanHistoryEntry = IDL.Record({
  'scanType' : ScanType,
  'summary' : ResultSummary,
  'target' : IDL.Text,
  'timestamp' : Time,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'getHistoryEntryByTarget' : IDL.Func([IDL.Text], [ScanHistoryEntry], []),
  'getScanHistory' : IDL.Func([], [IDL.Vec(ScanHistoryEntry)], []),
  'lookupDns' : IDL.Func([IDL.Text], [IDL.Text], []),
  'ping' : IDL.Func([], [IDL.Text], ['query']),
  'scanUrl' : IDL.Func([IDL.Text], [IDL.Text], []),
  'setSafeBrowsingApiKey' : IDL.Func([IDL.Text], [], []),
  'setVirusTotalApiKey' : IDL.Func([IDL.Text], [], []),
  'setWhoisApiKey' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ScanType = IDL.Variant({ 'dns' : IDL.Null, 'url' : IDL.Null });
  const ResultSummary = IDL.Record({
    'threatsFound' : IDL.Vec(IDL.Text),
    'recordType' : IDL.Text,
    'verdict' : IDL.Text,
    'resolverName' : IDL.Text,
    'recordValue' : IDL.Text,
    'riskScore' : IDL.Nat,
  });
  const Time = IDL.Int;
  const ScanHistoryEntry = IDL.Record({
    'scanType' : ScanType,
    'summary' : ResultSummary,
    'target' : IDL.Text,
    'timestamp' : Time,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'getHistoryEntryByTarget' : IDL.Func([IDL.Text], [ScanHistoryEntry], []),
    'getScanHistory' : IDL.Func([], [IDL.Vec(ScanHistoryEntry)], []),
    'lookupDns' : IDL.Func([IDL.Text], [IDL.Text], []),
    'ping' : IDL.Func([], [IDL.Text], ['query']),
    'scanUrl' : IDL.Func([IDL.Text], [IDL.Text], []),
    'setSafeBrowsingApiKey' : IDL.Func([IDL.Text], [], []),
    'setVirusTotalApiKey' : IDL.Func([IDL.Text], [], []),
    'setWhoisApiKey' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };